// generated by builder.sce: Please do not edit this file
// ------------------------------------------------------
sivp_path=get_file_path('loader.sce');
functions=[ 'vdofinfo';
            'sivp_formats';
            'imgread';
];
addinter(sivp_path+'/sivp.so','sivp',functions);
