#include "sivp_common.h"
#include <memory.h>
#include "stack-c.h"


void
get_codec_name (char *name, AVCodecContext * enc, int encode)
{
  const char *codec_name;
  AVCodec *p;
  char buf1[32];


  if (encode)
    p = avcodec_find_encoder (enc->codec_id);
  else
    p = avcodec_find_decoder (enc->codec_id);

  if (p)
    {
      codec_name = p->name;
      if (!encode && enc->codec_id == CODEC_ID_MP3)
	{
	  if (enc->sub_id == 2)
	    codec_name = "mp2";
	  else if (enc->sub_id == 1)
	    codec_name = "mp1";
	}
    }
  else if (enc->codec_id == CODEC_ID_MPEG2TS)
    {
      /* fake mpeg2 transport stream codec (currently not
         registered) */
      codec_name = "mpeg2ts";
    }
  else if (enc->codec_name[0] != '\0')
    {
      codec_name = enc->codec_name;
    }
  else
    {
      /* output avi tags */
      if (enc->codec_type == CODEC_TYPE_VIDEO)
	{
	  snprintf (buf1, sizeof (buf1), "%c%c%c%c",
		    enc->codec_tag & 0xff,
		    (enc->codec_tag >> 8) & 0xff,
		    (enc->codec_tag >> 16) & 0xff,
		    (enc->codec_tag >> 24) & 0xff);
	}
      else
	{
	  snprintf (buf1, sizeof (buf1), "0x%04x", enc->codec_tag);
	}
      codec_name = buf1;
    }

  sprintf (name, "%s", codec_name);
}


/**************************************************
 * Read video information from file
 **************************************************/
int
vdofinfo (char *filename, VdoFInfo * finfo)
{
  AVFormatContext *pFormatCtx = NULL;
  int i, videoStream;
  AVCodecContext *pCodecCtx = NULL;
/*   AVCodec *pCodec = NULL; */


   memset(finfo->log, 0, sizeof (finfo->log));

  // Register all formats and codecs
  av_register_all ();

  sprintf (finfo->filename, "%s", filename);

  // Open video file
  if (av_open_input_file (&pFormatCtx, filename, NULL, 0, NULL) != 0)
    {
      sprintf (finfo->log, "Couldn't open file.");
      goto loop_exit;		// Couldn't open file
    }

  // Retrieve stream information
  if (av_find_stream_info (pFormatCtx) < 0)
    {
      sprintf (finfo->log, "Couldn't find steam information, and maybe it isn't a video file.");
      goto loop_exit;		// Couldn't find stream information
    }

  // Dump information about file onto standard error
  //dump_format (pFormatCtx, 0, filename, FALSE);

  // Find the first video stream
  videoStream = -1;
  for (i = 0; i < pFormatCtx->nb_streams; i++)
    if (pFormatCtx->streams[i]->codec.codec_type == CODEC_TYPE_VIDEO)
      {
	videoStream = i;
	break;
      }

  if (videoStream == -1)
    {
      sprintf (finfo->log, "No video stream in file.");
      goto loop_exit;		// Didn't find a video stream
    }

  // Get a pointer to the codec context for the video stream
  pCodecCtx = &pFormatCtx->streams[videoStream]->codec;

/*   // Find the decoder for the video stream */
/*   pCodec = avcodec_find_decoder (pCodecCtx->codec_id); */
/*   if (pCodec == NULL) */
/*     { */
/*       sprintf (finfo->log, "No codec for this video file"); */
/*       goto loop_exit;		// Codec not found */
/*     } */

  // Hack to correct wrong frame rates that seem to be generated by some
  // codecs
  if (pCodecCtx->frame_rate > 1000 && pCodecCtx->frame_rate_base == 1)
    pCodecCtx->frame_rate_base = 1000;



  //copy the data to structure finfo
  finfo->file_size = pFormatCtx->file_size;
  finfo->width = pCodecCtx->width;
  finfo->height = pCodecCtx->height;
  finfo->bit_rate = pFormatCtx->bit_rate;
  finfo->duration = pFormatCtx->duration / AV_TIME_BASE;
  get_codec_name (finfo->codec_name, pCodecCtx, FALSE);
  sprintf (finfo->pixel_format,"%s", avcodec_get_pix_fmt_name(pCodecCtx->pix_fmt));
  sprintf (finfo->title, "%s", pFormatCtx->title);
  sprintf (finfo->author, "%s", pFormatCtx->author);
  sprintf (finfo->copyright, "%s", pFormatCtx->copyright);
  sprintf (finfo->comment, "%s", pFormatCtx->comment);


loop_exit:

  // Close the codec
  //    if(pCodecCtx)
  //      avcodec_close(pCodecCtx);

  // Close the video file
  if (pFormatCtx)
    av_close_input_file (pFormatCtx);

  if(strlen(finfo->log) == 0)
    return 0;
  else
    return -1;
}


/**************************************************
 * Inferface funtion for vdofinfo
 **************************************************/
int
int_vdofinfo(char * fname)
{
  int pos;
  char * psType[] ={ "type",
    "filename",
    "file_size",
    "width",
    "height",
    "codec_name",
    "pixel_format",
    "bit_rate",
    "duration",
    "frame_number",
    "title",
    "author",
    "copyright",
    "comment" };

  int mOne=1, nOne=1;
  int mTmp;
  char *strTmp;
  double dTmp;
  double *pdTmp;
  int m1,n1, l1; //for input
  int mL=14,nL=1, lL; //for output

  VdoFInfo Info;
  int minlhs=1, minrhs=1, maxlhs=1, maxrhs=1;
  

  CheckRhs(minrhs,maxrhs) ;
  CheckLhs(minlhs,maxlhs) ;

  GetRhsVar(1, "c", &m1, &n1, &l1);

  memset(&Info, 0, sizeof (Info));

  if(vdofinfo(cstk(l1), &Info) != 0) //read file info error
    {
       Scierror(999,"%s: Read video file information error.\r\n \t%s \r\n",fname, Info.log);
       return -1;
    }

 
   //create a tlist var for output
  CreateVar(2, "t", &mL, &nL, &lL);

  pos =1;  
  //create members of the list
  CreateListVarFromPtr(2,pos++,"S", &nL, &mL, psType);
  
  strTmp=Info.filename;
  mTmp =strlen(Info.filename);
  CreateListVarFromPtr(2,pos++,"c", &mTmp, &nOne, &strTmp); //filename

  dTmp = (double)(Info.file_size);
  pdTmp=&(dTmp); //only need once
  CreateListVarFromPtr(2,pos++,"d", &mOne, &nOne,&pdTmp); //file size

  dTmp = (double)(Info.width);
  CreateListVarFromPtr(2,pos++,"d", &mOne, &nOne,&pdTmp); //width

  dTmp = (double)(Info.height);
  CreateListVarFromPtr(2,pos++,"d", &mOne, &nOne,&pdTmp); //height

  strTmp=Info.codec_name;
  mTmp=strlen(Info.codec_name);
  CreateListVarFromPtr(2,pos++,"c", &mTmp, &nOne,&strTmp); //codec name
  
  strTmp=Info.pixel_format;
  mTmp=strlen(Info.pixel_format);
  CreateListVarFromPtr(2,pos++,"c", &mTmp, &nOne,&strTmp); //pixel format

  dTmp=(double)(Info.bit_rate);
  CreateListVarFromPtr(2,pos++,"d", &mOne, &nOne,&pdTmp); //bit rate

  dTmp=(double)(Info.duration);
  CreateListVarFromPtr(2,pos++,"d", &mOne, &nOne,&pdTmp); //duration

  dTmp=(double)(Info.frame_number);
  CreateListVarFromPtr(2,pos++,"d", &mOne, &nOne,&pdTmp); //frame number

  strTmp=Info.title;
  mTmp=strlen(strTmp);
  CreateListVarFromPtr(2,pos++,"c", &mTmp, &nOne,&strTmp); //title

  strTmp=Info.author;
  mTmp=strlen(strTmp);
  CreateListVarFromPtr(2,pos++,"c", &mTmp, &nOne,&strTmp); //author

  strTmp=Info.copyright;
  mTmp=strlen(strTmp);
  CreateListVarFromPtr(2,pos++,"c", &mTmp, &nOne,&strTmp); //copyright

  strTmp=Info.comment;
  mTmp=strlen(strTmp);
  CreateListVarFromPtr(2,pos++,"c", &mTmp, &nOne,&strTmp); //comment

  //  strTmp=Info.log;
  //  nTmp=strlen(strTmp);
  //  CreateListVarFromPtr(2,pos++,"c", &mTmp, &nOne,&strTmp); //log



  /*  Return variables  */
  LhsVar(1) = 2;
  return 0;


}

