// This file is released into the public domain
// Generated by builder.sce : Please, do not edit this file
// cleaner.sce
// ------------------------------------------------------
curdir = pwd();
cleaner_path = get_file_path('cleaner.sce');
chdir(cleaner_path);
// ------------------------------------------------------
if fileinfo('loader.sce') <> [] then
  mdelete('loader.sce');
end
// ------------------------------------------------------
if fileinfo('libsivp.so') <> [] then
  mdelete('libsivp.so');
end
// ------------------------------------------------------
if fileinfo('libsivp.c') <> [] then
  mdelete('libsivp.c');
end
// ------------------------------------------------------
chdir(curdir);
// ------------------------------------------------------
